version: "3.5"

services:
  php:
    build: ./build
    container_name: my-comics-php
    user: "${USER_ID}"
    volumes:
      - ./:/app

  mysql:
    image: mysql:5.7
    container_name: my-comics-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  mysql: