version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: my-comics-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./build/nginx/app.conf:/etc/nginx/conf.d/site.conf

  php:
    build: ./build/php
    container_name: my-comics-php
    user: "${USER_ID}"
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:5.7
    container_name: my-comics-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  mysql: