GET http://my-comics.test/api/comics/1
Accept: */*
Origin: localhost
Cache-Control: no-cache

###

GET http://my-comics.test/api/comics?per_page=10&page=1
Accept: */*
Origin: localhost
Cache-Control: no-cache

###
