###########
### Api ###
###########
api_comics_get_by_id:
    path: /api/comics/{id}
    controller: App\Controller\Api\Comics::getById
    methods: GET|HEAD

api_comics_get_all:
    path: /api/comics
    controller: App\Controller\Api\Comics::getAll
    methods: GET|HEAD

api_comics_post:
    path: /api/comics
    controller: App\Controller\Api\Comics::post
    methods: POST

api_publishers_get_by_id:
    path: /api/publishers/{id}
    controller: App\Controller\Api\Publishers::getById
    methods: GET|HEAD

api_publishers_get_all:
    path: /api/publishers
    controller: App\Controller\Api\Publishers::getAll
    methods: GET|HEAD

api_images_get_by_id:
    path: /api/images/{id}
    controller: App\Controller\Api\Images::getById
    methods: GET|HEAD

api_statistics_get_all:
    path: /api/statistics
    controller: App\Controller\Api\Statistics::getAll
    methods: GET|HEAD

###########
### Web ###
###########
web_base:
    path: /
    controller: App\Controller\Web\Collection::overview
    methods: GET

web_collection_overview:
    path: /collection/overview
    controller: App\Controller\Web\Collection::overview
    methods: GET

web_collection_add_comic:
    path: /collection/add-comic
    controller: App\Controller\Web\Collection::addComic
    methods: GET

web_collection_create_comic:
    path: /collection/add-comic
    controller: App\Controller\Web\Collection::postComic
    methods: POST

web_collection_show_comic:
    path: /collection/overview/{id}
    controller: App\Controller\Web\Collection::show
    methods: GET

web_comics_edit:
    path: /collection/overview/{id}/edit
    controller: App\Controller\Web\Collection::edit
    methods: POST

web_comics_remove:
    path: /collection/overview/{id}/remove
    controller: App\Controller\Web\Collection::remove
    methods: DELETE

web_statistic_comics:
    path: /statistic/comics
    controller: App\Controller\Web\Statistic::getComicStatistics
    methods: GET

web_statistic_publishers:
    path: /statistic/publishers
    controller: App\Controller\Web\Statistic::getPublisherStatistics
    methods: GET