###########
### Api ###
###########
api_comics_get:
    path: /api/comics/{id}
    controller: App\Controller\Api\Comics::getById
    methods: GET|HEAD

api_comics_list:
    path: /api/comics
    controller: App\Controller\Api\Comics::getAll
    methods: GET|HEAD

api_comics_post:
    path: /api/comics
    controller: App\Controller\Api\Comics::post
    methods: POST

api_comics_delete:
    path: /api/comics/{id}
    controller: App\Controller\Api\Comics::delete
    methods: DELETE

api_comics_put:
    path: /api/comics/{id}
    controller: App\Controller\Api\Comics::put
    methods: PUT

api_publishers_get_by_id:
    path: /api/publishers/{id}
    controller: App\Controller\Api\Publishers::getById
    methods: GET|HEAD

api_publishers_get_all:
    path: /api/publishers
    controller: App\Controller\Api\Publishers::getAll
    methods: GET|HEAD

api_images_get:
    path: /api/images/{id}
    controller: App\Controller\Api\Images::getById
    methods: GET|HEAD

api_images_post:
    path: /api/images
    controller: App\Controller\Api\Images::post
    methods: POST

api_statistics_get_all:
    path: /api/statistics
    controller: App\Controller\Api\Statistics::getAll
    methods: GET|HEAD

api_comic_vine_id_post:
    path: /api/comic/comic_vine_id
    controller: App\Controller\Api\Comics::postComicVineId
    methods: POST

###########
### Web ###
###########
web_base:
    path: /
    controller: App\Controller\Web\Collection::overview
    methods: GET

web_collection_overview:
    path: /collection/overview
    controller: App\Controller\Web\Collection::overview
    methods: GET

web_collection_add_comic:
    path: /collection/add-comic
    controller: App\Controller\Web\Collection::addComic
    methods: GET

web_collection_show_comic:
    path: /collection/overview/{id}
    controller: App\Controller\Web\Collection::show
    methods: GET

web_comics_edit:
    path: /collection/overview/{id}/edit
    controller: App\Controller\Web\Collection::edit
    methods: POST

web_statistic_comics:
    path: /statistic/comics
    controller: App\Controller\Web\Statistic::getComicStatistics
    methods: GET

web_statistic_publishers:
    path: /statistic/publishers
    controller: App\Controller\Web\Statistic::getPublisherStatistics
    methods: GET