###########
### Api ###
###########
api_comics_get_by_id:
    path: /api/comics/{id}
    controller: App\Controller\Api\Comics::getById
    methods: GET|HEAD

api_comics_post:
    path: /api/comics
    controller: App\Controller\Api\Comics::post
    methods: POST

api_publishers_get_by_id:
    path: /api/publishers/{id}
    controller: App\Controller\Api\Publishers::getById
    methods: GET|HEAD

api_publishers_get_all:
    path: /api/publishers
    controller: App\Controller\Api\Publishers::getAll
    methods: GET|HEAD

api_images_get_by_id:
    path: /api/images/{id}
    controller: App\Controller\Api\Images::getById
    methods: GET|HEAD

###########
### Web ###
###########
web_comics_list:
    path: /
    controller: App\Controller\Web\Comics::list
    methods: GET

web_comics_show:
    path: /comics/{id}
    controller: App\Controller\Web\Comics::show
    methods: GET

web_comics_edit:
    path: /comics/{id}/edit
    controller: App\Controller\Web\Comics::edit
    methods: POST

web_comics_remove:
    path: /comics/{id}/remove
    controller: App\Controller\Web\Comics::remove
    methods: DELETE