issues:
    path: /issues/{id}
    controller: App\Controller\Issues::getById
    methods: GET|HEAD

issues_get_all:
    path: /issues
    controller: App\Controller\Issues::getAll
    methods: GET|HEAD

publishers:
    path: /publishers/{id}
    controller: App\Controller\Publishers::getById
    methods: GET|HEAD

publishers_get_all:
    path: /publishers
    controller: App\Controller\Publishers::getAll
    methods: GET|HEAD

comics:
    path: /comics
    controller: App\Controller\Comics::addComic
    methods: POST